### ISSUE TITLE
请问一下为什么使用 System.gc()

### ISSUE THREAD

**Issue by qsqiushi** [lidashuang1996/p6e_netty_websocket_client#7]
`
    @Override
    public void __onMessageText__(P6eWebSocketClient websocket, String message) {
        this.onMessageText(websocket, message);
        System.gc(); // 回收掉生成的一次性的对象，避免内存泄漏
    }`
之前遇到过 System.gc()会触发Full GC导致 Old GC 过多的问题
请问一下在此处为什么要这么用，每次收到消息都要gc一次频率是否有些太高了，释放的又是哪些对象？

**Comment by qsqiushi** [comment]
当频率为每秒20次的时候，就出现cpu占用情况明显上升的情况，此处gc建议注释掉

**Comment by lidashuang1996** [comment]
在您提出问题的时候我竟然没有看到邮件，在您关闭问题的时候我才看到邮件，抱歉！
